# Generated by Django 3.2.12 on 2024-04-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(default=None, max_length=50, null=True)),
                ('country', models.CharField(default=None, max_length=50, null=True)),
                ('zipCode', models.CharField(default=None, max_length=50, null=True)),
                ('email', models.CharField(max_length=100)),
                ('portal', models.CharField(max_length=500)),
            ],
        ),
    ]
