# Generated by Django 3.2.12 on 2024-04-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0003_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='officeLocation',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='currency',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
